sec_morphology_type:
  opt_morphology:
  - type_analytic
  opt_synthetic_type:
  - type_fusional
  opt_word_order:
  - VSO
sec_universal_features:
  bools:
    feat_gender: true
    feat_number: true
  settings:
    feat_gender:
    - gen_neutral
    feat_number:
    - num_singular
    - num_dual
