morphology:
  sec_noun_syntax:
    selected_matrix_dims:
    - univ|feat_gender
    - univ|feat_number
    - local|feat_case
    markers:
      gen_masculine+num_singular+case_nominative:
      - marker: + ∅ / C_#
      gen_masculine+num_plural+case_nominative:
      - marker: "+ ɨ / H_#\r\n+ i / S_#"
      gen_feminine+num_singular+case_nominative:
      - marker: "+ a / H_#\r\n+ ja / S_#"
      gen_feminine+num_plural+case_nominative:
      - marker: "+ ɨ / H_#\r\n+ i / S_#"
      gen_neutral+num_singular+case_nominative:
      - marker: "+ o / H_#\r\n+ e / S_#"
      gen_neutral+num_plural+case_nominative:
      - marker: "+ a / H_#\r\n+ ja / S_#"
phonology:
  inventory_consonants:
  - p
  - b
  - t
  - d
  - k
  - g
  - ts
  - tʃ
  - tɕ
  - m
  - n
  - r
  - f
  - v
  - s
  - z
  - ɕ
  - ʂ
  - ʐ
  - x
  - j
  - l
  inventory_vowels:
  - i
  - ɨ
  - u
  - e
  - o
  - ə
  - ɛ
  - a
  - ɑ
  inventory:
  - b
  - d
  - f
  - g
  - h
  - j
  - k
  - l
  - m
  - n
  - p
  - r
  - s
  - t
  - ts
  - tɕ
  - tʃ
  - v
  - x
  - z
  - ɕ
  - ʂ
  - ʐ
  - a
  - e
  - i
  - o
  - u
  - ɑ
  - ə
  - ɛ
  - ɨ
  weights:
    consonants:
      b: 38
      p: 10
      ɕ: 10
      d: 35
      f: 10
      g: 12
      j: 10
      k: 37
      l: 42
      m: 30
      n: 38
      r: 62
      s: 77
      ʂ: 26
      t: 44
      tɕ: 10
      ts: 10
      tʃ: 10
      v: 10
      x: 26
      z: 32
      ʐ: 10
    vowels:
      i: 10
      a: 10
      ɑ: 10
      e: 10
      ə: 10
      ɛ: 10
      ɨ: 10
      o: 10
      u: 10
  custom_order: b i p y
  categories:
    B:
      comment: Labials
      symbols:
      - p
      - b
      - m
      - f
      - v
    F:
      comment: Fricatives
      symbols:
      - f
      - v
      - s
      - z
      - ɕ
      - ʂ
      - ʐ
      - x
    G:
      comment: Gutturals/Back
      symbols:
      - k
      - g
      - x
    K:
      comment: Coronals
      symbols:
      - t
      - d
      - ts
      - tʃ
      - tɕ
      - n
      - r
      - s
      - z
      - l
    L:
      comment: Liquids/Approximants
      symbols:
      - r
      - j
      - l
    N:
      comment: Nasals
      symbols:
      - m
      - n
    P:
      comment: Plosives
      symbols:
      - p
      - b
      - t
      - d
      - k
      - g
      - ts
      - tʃ
      - tɕ
sec_morphology_type:
  opt_morphology:
  - type_analytic
  opt_synthetic_type:
  - type_fusional
  opt_word_order:
  - SVO
sec_universal_features:
  bools:
    feat_gender: true
    feat_number: true
    feat_alignment: true
  settings:
    feat_gender:
    - gen_masculine
    - gen_feminine
    - gen_neutral
    feat_number:
    - num_singular
    - num_plural
    feat_alignment:
    - align_nominative
sec_noun_syntax:
  bools:
    feat_case: true
    feat_number: true
  settings:
    feat_case:
    - case_nominative
    - case_genitive
    - case_dative
    - case_accusative
    - case_instrumental
    - case_locative
    feat_number:
    - num_singular
sec_verb_syntax:
  bools:
    feat_tense: true
    feat_mood: true
  settings:
    feat_tense:
    - tense_past
    - tense_present
    feat_mood:
    - mood_imperative
    - mood_indicative
sec_adj_syntax:
  bools:
    feat_agreement: true
